pub usingnamespace @import("dec/alpha_dec.zig");
pub usingnamespace @import("dec/buffer_dec.zig");
pub usingnamespace @import("dec/frame_dec.zig");
pub usingnamespace @import("dec/idec_dec.zig");
pub usingnamespace @import("dec/io_dec.zig");
pub usingnamespace @import("dec/tree_dec.zig");
pub usingnamespace @import("dec/quant_dec.zig");
pub usingnamespace @import("dec/vp8_dec.zig");
pub usingnamespace @import("dec/vp8l_dec.zig");
